###############################################################################
# Stage -- Unit Testing
###############################################################################
# 
# Overrides:
# 
# 1) nrtk specific notebooks.
#
###############################################################################

notebooks:
  parallel:
    matrix:
      # Sequences combinatorically combine within a list entry
      - NOTEBOOK_DIR: "examples"
        NOTEBOOK_FILE: [
          "coco_scorer.ipynb",
          "perturbers.ipynb",
          "simple_generic_generator.ipynb",
          "simple_pybsm_generator.ipynb"
        ]
      - NOTEBOOK_DIR: "examples/pybsm"
        NOTEBOOK_FILE: [
          "pybsm_test.ipynb"
        ]